Upgrade Boost for KUKSA.val Server
Background reason:

Newer gcc versions give more warnings, and we treat warnings as errors.
We get a warning on boost that has been fixed in recent Boost versions

/home/erik/kuksa.val/kuksa-val-server/build/_deps/boost-build/include/boost/thread/pthread/thread_data.hpp:61:19: error: comparison of integer expressions of different signedness: ‘std::size_t’ {aka ‘long unsigned int’} and ‘long int’ [-Werror=sign-compare]
   61 |           if (size<PTHREAD_STACK_MIN) size=PTHREAD_STACK_MIN;
      |                   ^
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors